### ISSUE TITLE
Problems with "chunk cache"

### ISSUE THREAD

**Issue by codewarrior0** [Khroki/MCEdit-Unified#334]
Commit 95963c5316981219e8bd2c4f2904d901c97a2538 does not actually add a chunk cache. Chunks are already cached in _loadedChunkData. The purpose of _loadedChunks is to find out via weakrefs whether any clients of MCInfdevOldLevel are holding references to a chunk, to find out if it is safe to evict a cached chunk from _loadedChunkData once the number of chunks exceeds loadedChunkLimit.

That commit effectively bypasses the limit by holding an unlimited number of chunks in _loadedChunks.

The problem I think you are trying to address is that when chunks are evicted from _loadedChunkData, they are not evicted in any particular order - whichever one comes first in the dict implementation gets evicted. This will clearly lead to "cache thrashing" when the most recently loaded chunks are repeatedly evicted and then loaded again. The proper solution is to make _loadedChunkData know which chunks have been least recently used (an LRU cache, a well-known data structure). I had meant to make that change for some time - if you look at https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/cachefunc.py, you'll find an LRU cache implementation there. It just has to be adapted into a dict-like data structure (or changed in such a way that when entries are evicted, the chunk can be written to unsavedWorkFolder if needed) instead of one that wraps a function.

One problem this commit creates is that MCInfdevOldLevel will not know if it is safe to evict a chunk from the cache. If the cleanup is triggered while any client still has a reference to a chunk, that chunk will be "lost" - MCInfdevOldLevel won't know about it any more and any changes made to that chunk won't have any effect. If MCInfdevOldLevel is asked for that chunk again it will return an entirely new AnvilChunk with an entirely new AnvilChunkData behind it. This is precisely the problem that the weakref dict _loadedChunks is meant to solve.

**Comment by codewarrior0** [comment]
This all would probably be clearer if _loadedChunks were renamed to _referencedChunks and _loadedChunkData to _cachedChunks

**Comment by Khroki** [comment]
We'll let Rubisk know, although if you see something you want to fix, we always welcome pull requests.

**Comment by codewarrior0** [comment]
This is a change that also needs to be made in MCEdit 2, so I'll backport it for you when I get around to it.

Thinking on it some more, that problem in the last paragraph will affect any algorithm which has to load several chunks at once and then modify them. Any algorithm which modifies a chunk and its neighbors will be affected. In particular, the old lighting algorithm you use does this a lot. I suggest reverting this change.

**Comment by Rubisk** [comment]
I have a hard time understanding what you're saying, but I'm assuming this is what you mean:

-loadedChunkData holds the actual chunks.
-loadedChunks holds just some wrappers around the chunks, just to figure out what chunks are not being referenced by other algorithms (figure out what cna't be decached)
-Once all pointers to a chunk are lost, it will get removed out of loadedChunks
-Once there's more then 400 chunkData's, it all clean up those that aren't in loadedChunks

And know I made it so it takes time, not no-references, to remove them out of loadedChunks. I guess that's indeed bad. But can't we just add a timeLastChanged to all AnvilChunkData objects and sort the dictionary by that before decaching (dunno if that's code-technically a thing, but otherwise make do it manually)?

**Comment by codewarrior0** [comment]
>But can't we just add a timeLastChanged to all AnvilChunkData objects and sort the dictionary by that before decaching (dunno if that's code-technically a thing, but otherwise make do it manually)?

It would be better if you recorded the time of last access rather than last modification, because using last modification only will lead to thrashing on unmodified chunks.

Yes, adding the timestamp to each AnvilChunkData and sorting on that before decaching would have a similar outcome, but I don't like that for two reasons:
-  You're putting a detail of the cache implementation on each chunk. The cache should be a self-contained object so you can easily swap it out for a different type of cache for experimenting.
- There is no need to sort the dictionary (see the implementation in lru_cache.py)

**Comment by Rubisk** [comment]
My python/programming knowledge isn't at all good enough to make any sense out of this: https://github.com/Khroki/MCEdit-Unified/blob/master/pymclevel/cachefunc.py

I understand what decoraters do, sort-of, but have no idea how this caches stuff, or what it even caches. Let alone being able to merge that over to a dictionary system.

**Comment by codewarrior0** [comment]
It caches the results of a function, keyed on the arguments to that function. It has to be changed to notify its client when a result is about to be decached.

If you don't understand it, don't worry about it. Like I said, I need to do this for MCEdit 2 also. All you have to do is revert your changes to the chunk cache and wait for a patch.

**Comment by Rubisk** [comment]
I think I reverted everything, shame github won't let me revert a merge. 3c509e076bf0237f42bfe5f586197226581bf9e9 3ee22e7909532220b761187eef725c25636dc93d

**Comment by codewarrior0** [comment]
All right. Expect a patch in the next couple of days.

Do you happen to know which filter you were using for benchmarks while you were working on this?

**Comment by Rubisk** [comment]
An alchemy (vary) filter thay I used before I implemented varied brushes - it has a huge amount of setBlockAt/blockAt calls/operation:http://www.brightmoore.net/mcedit-filters-1/alchemy

**Comment by codewarrior0** [comment]
Well, you were right about one thing. It's spending a lot of time in getChunk creating new AnvilChunks, even when the AnvilChunkDatas are already loaded. Changing _loadedChunks into a regular dict is still wrong, though, but there's something else you can do. Just keep the recently loaded chunks in another place, like a deque called recentChunks, and make sure it gets cleared whenever _loadedChunkData needs to be cleared. 

I'll take care of that when I backport the new lru_cache for you.

![profile](https://cloud.githubusercontent.com/assets/307683/6653571/8ba53912-ca3c-11e4-8c27-8613203254cc.png)

**Comment by codewarrior0** [comment]
I'm still working on the modified lru_cache, by the way. I haven't sent it to you because I wasn't confident enough in my changes, but I think I've just worked out the last kinks. I had to add a should_decache callback to find out if a chunk is safe to decache, a will_decache callback to have the chunk written to disk before it gets decached, and a pair of store/decache functions to explicitly control the cache when creating new chunks and moving through the RevisionHistory. I also had to make sure the cache remains consistent whenever the user_function throws an exception.

There's probably a better library out there for persistent disk-backed caches (something like klepto maybe) but this should work for the specific case of writing a chunk into a region file. There may be other uses you can find for it.

**Comment by Estevo-Aleixo** [comment]
What did you use to create that graph?

**Comment by codewarrior0** [comment]
Python profiler, gprof2dot.py and graphviz, pretty much.

```
#!/bin/bash -x
#PYTHON=python
PYTHON=/c/python27/python

python -m cProfile -o /tmp/profile.dat "$@"
set -e # exit on error for following commands
$PYTHON ~/bin/gprof2dot.py -f pstats /tmp/profile.dat > /tmp/profile.dot
dot -Tpng -o /tmp/profile.png /tmp/profile.dot
start /tmp/profile.png
```

**Comment by TrazLander** [comment]
Don't know if this was fully resolved, but assuming it is and closing this as it's no longer active.

**Comment by Rubisk** [comment]
No, I still need to do this.

**Comment by codewarrior0** [comment]
>I'd like to just write it once, instead of one time per world type (anvil, alpha, pocket etc.)

I did it by separating the level-specific code from the world editing code and having a WorldEditor class that contains an AnvilWorldAdapter class, but to do this I had to rewrite the entire pymclevel and rename it to mceditlib. :P

I won't bother sending you the lru_cache. You can come and steal it if you want. The speed gain is incredibly minor compared to just using a dict. The recentLoadedChunks patch I sent a while ago had a more dramatic effect.
